[package]
name = "ASCII-IMAGE"
version = "0.1.0"
edition = "2021"

[dependencies]
nokhwa = { version = "0.10.4", features = ["input-native", "output-threaded"], git = "https://github.com/kendfrey/nokhwa.git", branch = "0.10" }
